# permissions for end users to view operatorpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorpipeline-viewer-role
rules:
- apiGroups:
  - certification.redhat.com
  resources:
  - operatorpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certification.redhat.com
  resources:
  - operatorpipelines/status
  verbs:
  - get
