# permissions for end users to edit operatorpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorpipeline-editor-role
rules:
- apiGroups:
  - certification.redhat.com
  resources:
  - operatorpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certification.redhat.com
  resources:
  - operatorpipelines/status
  verbs:
  - get
