name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    name: sanity
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: sudo rm -rf /usr/local/bin/kustomize
    - run: make test-sanity
